name: GitHub Pages

on:
  push:
    branches:
      - loveit
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
          extended: true

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: |
          (rm -fv ./assets/css/_custom.scss && patch -p0 -i ./assets/css/_custom.patch)
          hugo --minify --noBuildLock --baseURL 'https://crdinusc.eu.org' | tee /tmp/gohugo_render.log
          if [ -r /tmp/gohugo_render.log ]; then
              { read GRAB_TITLE < ./public/robots.txt && export EXTENDED_TITLE="${GRAB_TITLE##\#\ }"; }
              sed -e "1s|.*|${EXTENDED_TITLE}|" \
                  -e "2s|.*|$(printf '%0.s=' $(seq 1 ${#EXTENDED_TITLE}))|" \
                  -e '3d;4d' \
              /tmp/gohugo_render.log > ./public/gohugo-codegen-perf.txt
          fi
          (cd ./public/ && \
           curl -LO 'https://github.com/owl4ce/owl4ce.github.io/releases/latest/download/NUMQUAM_SCIRE.iso')

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/loveit' }}
        env:
          GIT_AUTHOR_DATE: '2021-01-02T07:13:52Z'
          GIT_COMMITTER_DATE: '2021-01-02T07:13:52Z'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '.github,**/*.asc'
          publish_dir: ./public
          force_orphan: true
          cname: crdinusc.eu.org
